trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx2g'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: $(HOME)/.m2/repository
    restoreKeys: |
      maven | "$(Agent.OS)"

- script: mvn -B -DskipTests=false test
  displayName: 'Run mvn test'
  env:
    MAVEN_OPTS: $(MAVEN_OPTS)

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven Test Results'
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/allure-results'
    ArtifactName: 'allure-results'
    publishLocation: 'Container'
